---
title: "Table Shells - n is 560"
author: "Adam Jauregui"
date: "December 14, 2018"
output: word_document
---

```{r setup, include=FALSE}
library(readr)
library(ggplot2)
library(arsenal)
library(tableone)
aim3.dat.clean <- read_csv("C:/Users/Adam/Documents/BSRI/TIP Stuff/aim3_Dat_clean_correct.csv", 
                         col_types = cols(ATF_AdmDate = col_date(format = "%m/%d/%Y"), 
                                          ATF_BookingDate = col_date(format = "%m/%d/%Y"), 
                                          ATF_ComponentsTXDate1 = col_date(format = "%m/%d/%Y"), 
                                          ATF_ComponentsTXDate2 = col_date(format = "%m/%d/%Y"), 
                                          ATF_ComponentsTXDate3 = col_date(format = "%m/%d/%Y"), 
                                          ATF_ComponentsTXDate4 = col_date(format = "%m/%d/%Y"), 
                                          ATF_ComponentsTXDate5 = col_date(format = "%m/%d/%Y"), 
                                          ATF_ComponentsTXDate6 = col_date(format = "%m/%d/%Y"), 
                                          ATF_ComponentsTXDate7 = col_date(format = "%m/%d/%Y"), 
                                          ATF_DschgDate = col_date(format = "%m/%d/%Y"), 
                                          ATF_EstDateDelivery = col_date(format = "%m/%d/%Y"), 
                                          ATF_HIVStatusBookingDate = col_date(format = "%m/%d/%Y"), 
                                          ATF_HIVStatusDelvAdmitDate = col_date(format = "%m/%d/%Y"), 
                                          ATF_HIVStatusOthTestDate = col_date(format = "%m/%d/%Y"), 
                                          ATF_PMTCTStartDate = col_date(format = "%m/%d/%Y"), 
                                          ATF_TodayDate = col_date(format = "%m/%d/%Y"), 
                                          ChartAbstrationDate = col_date(format = "%m/%d/%Y"), 
                                          ConsentDate = col_date(format = "%m/%d/%Y"), 
                                          CreatedDate = col_date(format = "%m/%d/%Y")))
View(aim3.dat.clean)

#subset out Groote/Schurr hospitals
aim3_chris.king<-subset(aim3.dat.clean,
                              LOCATION=="Chris Hani" | 
                                LOCATION=="King Edward")

#add gestation weeks
gest.wks.tri<-cut(aim3_chris.king$ATF_GestAgeWks,
              breaks=c(-Inf,13,25,Inf),
              label=c("<14","14-25",">25"),
              right=FALSE)
aim3_chris.king$gest.wks.tri<-gest.wks.tri
aim3_chris.king<-aim3_chris.king[c(1:16,115,17:114)]
aim3_chris.king<-aim3_chris.king[-c(112)]

#rename column
colnames(aim3_chris.king)[
  colnames(aim3_chris.king)=="ATF_Transfused.x"
]<-"ATF_Transfused"

#recalculate stay length column
aim3_chris.king$Stay_Length<-as.numeric(
  aim3_chris.king$ATF_DschgDate)-as.numeric(
    aim3_chris.king$ATF_AdmDate)

#subset out those who are not transfused
aim3_chki.tx.conf<-subset(x=aim3_chris.king,
                          subset=!(rowSums(aim3_chris.king[c(112:114)])==0))
```

##Table 1 - Characteristics of Study Population

```{r table1, echo=FALSE,warning=FALSE}
#Print out Table 1
#(aggregated)
table1.df<-data.frame(Age_of_Mother=aim3_chki.tx.conf$ATF_Age,
                      Race=aim3_chki.tx.conf$ATF_Race,
                      Gravidity=aim3_chki.tx.conf$ATF_Gravidity,
                      Parity=aim3_chki.tx.conf$ATF_Parity,
                      Gestation_Age_Weeks=
                        aim3_chki.tx.conf$ATF_GestAgeWks,
                      Booking_Status_At_Admission=
                        aim3_chki.tx.conf$ATF_BookingStatusAtAdm,
                      Prenatal_Visits=
                        aim3_chki.tx.conf$ATF_NumVisitsAntenatalClinic,
                      Gestation_Age_Weeks_Grouped=
                        aim3_chki.tx.conf$gest.wks.tri,
                      Length_of_Stay=
                        aim3_chki.tx.conf$Stay_Length,
                      Alive_at_Discharge=
                        aim3_chki.tx.conf$ATF_AliveAtDschg)
listvars<-c("Age_of_Mother","Race","Gravidity","Parity",
            "Gestation_Age_Weeks",
            "Booking_Status_At_Admission",
            "Gestation_Age_Weeks_Grouped",
            "Length_of_Stay",
            "Prenatal_Visits","Alive_at_Discharge")
catvars<-c("Race","Booking_Status_At_Admission",
           "Gestation_Age_Weeks_Grouped",
           "Alive_at_Discharge")
nonnormalvars<-c("Gravidity","Parity","Prenatal_Visits",
                 "Length_of_Stay")
table1<-CreateTableOne(vars=listvars,
                       data = table1.df,
                       factorVars = catvars,
                       includeNA = TRUE)
table1.doc<-print(table1,nonnormal = nonnormalvars)
#(by hospital)
table1.df<-data.frame(Location=aim3_chki.tx.conf$LOCATION,
                      Age_of_Mother=aim3_chki.tx.conf$ATF_Age,
                      Race=aim3_chki.tx.conf$ATF_Race,
                      Gravidity=aim3_chki.tx.conf$ATF_Gravidity,
                      Parity=aim3_chki.tx.conf$ATF_Parity,
                      Gestation_Age_Weeks=
                        aim3_chki.tx.conf$ATF_GestAgeWks,
                      Booking_Status_At_Admission=
                        aim3_chki.tx.conf$ATF_BookingStatusAtAdm,
                      Prenatal_Visits=
                        aim3_chki.tx.conf$ATF_NumVisitsAntenatalClinic,
                      Gestation_Age_Weeks_Grouped=
                        aim3_chki.tx.conf$gest.wks.tri,
                      Length_of_Stay=
                        aim3_chki.tx.conf$Stay_Length,
                      Alive_at_Discharge=
                        aim3_chki.tx.conf$ATF_AliveAtDschg)
listvars<-c("Age_of_Mother","Race","Gravidity","Parity",
            "Gestation_Age_Weeks",
            "Booking_Status_At_Admission",
            "Gestation_Age_Weeks_Grouped",
            "Length_of_Stay",
            "Prenatal_Visits","Alive_at_Discharge")
catvars<-c("Location",
           "Race","Booking_Status_At_Admission",
           "Gestation_Age_Weeks_Grouped",
           "Alive_at_Discharge")
nonnormalvars<-c("Gravidity","Parity","Prenatal_Visits",
                 "Length_of_Stay")
table1<-CreateTableOne(vars=listvars,data = table1.df,
                       factorVars = catvars,includeNA = TRUE,
                       strata = "Location",test=FALSE)
print(table1,nonnormal = nonnormalvars)
```

##Table 1 Plots
```{r table1 plots,echo=FALSE,warning=FALSE}
#Section 1 - Demographics
#1. Age:
ggplot(aim3_chki.tx.conf,aes(ATF_Age)) + 
  geom_histogram(binwidth=1) + 
  labs(x="Age in Years",y="counts",title="Age of Mothers")
ggplot(aim3_chki.tx.conf,aes(LOCATION,ATF_Age)) + 
  geom_boxplot(fill=c("chocolate","khaki")) +
  labs(x="Location",y="Years",
       title="Age of Mothers by Location")
#
#6. Race / ethnic origin:
ggplot(aim3_chki.tx.conf,aes(ATF_Race)) +
  geom_bar(fill=c("black","white","brown","yellow","gray")) +
  labs(x="Race",y="counts",title="Race of Mothers") +
  scale_x_discrete(labels=c("Black","White","Coloured","Asian","NA")) +
  geom_text(stat='count',aes(label=..count..,vjust=-.2))
ggplot(aim3_chki.tx.conf, aes(fill=ATF_Race, x=LOCATION)) + 
  geom_bar() + 
  scale_fill_manual(values=c("01 Black"="black",
                             "02 White"="white",
                             "03 Coloured"="brown",
                             "04 Asian"="yellow",
                             "NA"="gray"),
                    name="Race") +
  labs(x="Hospital",y="counts",title="Race of Mothers by Location")
```

##Table 2

```{r table2,echo=FALSE,warning=FALSE}
table2.df<-data.frame(Transfused=
                        aim3_chki.tx.conf$ATF_Transfused,
                      Blood_Transfusion_Rationale=
                        aim3_chki.tx.conf$ATF_MedicalRationaleForTx,
                      Anemic_Current_Pregnancy=
                        aim3_chki.tx.conf$ATF_IdAnemicDuringCurrPreg,
                      Anemia_Etiology=
                        aim3_chki.tx.conf$ATF_ChronicAnemiaType,
                      Bleeding_this_Pregnancy=
                        aim3_chki.tx.conf$ATF_BleedingThisPreg,
                      Hemorrhage_Cause=
                        aim3_chki.tx.conf$ATF_HemorrhageCause)
listvars<-c("Transfused",
            "Blood_Transfusion_Rationale","Anemic_Current_Pregnancy",
            "Anemia_Etiology","Bleeding_this_Pregnancy",
            "Hemorrhage_Cause")
catvars<-c("Transfused",
           "Blood_Transfusion_Rationale","Anemic_Current_Pregnancy",
           "Anemia_Etiology","Bleeding_this_Pregnancy",
           "Hemorrhage_Cause")
table2<-CreateTableOne(vars=listvars,data=table2.df,factorVars = catvars,
                       includeNA = TRUE)
table2

```

##Table 3

```{r table3,echo=FALSE,warning=FALSE}
###Table 3 Complications During Current Pregnancy###
table3.df<-data.frame(Complications_this_Pregnancy=
                        aim3_chki.tx.conf$ATF_CompsThisPreg,
                      Type_of_Complications_this_Pregnancy=
                        aim3_chki.tx.conf$ATF_CompsThisPregType,
                      Complications_this_Admission=
                        aim3_chki.tx.conf$ATF_CompsThisAdm,
                      Type_of_Complications_this_Admission=
                        aim3_chki.tx.conf$ATF_CompsThisAdmType)
listvars<-c("Complications_this_Pregnancy",
            "Type_of_Complications_this_Pregnancy",
            "Complications_this_Admission",
            "Type_of_Complications_this_Admission")
catvars<-c("Complications_this_Pregnancy",
           "Type_of_Complications_this_Pregnancy",
           "Complications_this_Admission",
           "Type_of_Complications_this_Admission")
table3<-CreateTableOne(vars=listvars,data = table3.df,
                       factorVars = catvars,
                       includeNA = TRUE)
table3
```

##Table 4 - Miscellaneous

```{r table4,echo=FALSE,warning=FALSE}
table4.df<-data.frame(Previous_Transfusion=
                        aim3_chki.tx.conf$ATF_TransfusePriorToCurr,
                      Previous_Transfusion_When=
                        aim3_chki.tx.conf$ATF_TransfusedPriorWhen,
                      Anemia_Treatment=
                        aim3_chki.tx.conf$ATF_OnHematinicRxDuringPreg,
                      Who_Ordered_Transfusion=
                        aim3_chki.tx.conf$ATF_TxHighestLevelDiscuss,
                      Patient_Transfused_Where=
                        aim3_chki.tx.conf$ATF_PtTransfusedAt,
                      Where_Patient_Transfused_Start=
                        aim3_chki.tx.conf$ATF_WherePtTxStart,
                      PreTransfusion_Hemoglobin=
                        aim3_chki.tx.conf$ATF_LastHemoglobinPriorTx,
                      Hemoglobin_Method_Used=
                        aim3_chki.tx.conf$ATF_HbMethodUsed,
                      Where_Results_Obtained_Before_Transfusion=
                        aim3_chki.tx.conf$ATF_WhereResultsObtainedPriorTx)
listvars<-c("Previous_Transfusion","Previous_Transfusion_When",
            "Anemia_Treatment","Who_Ordered_Transfusion",
            "Patient_Transfused_Where",
            "Where_Patient_Transfused_Start",
            "PreTransfusion_Hemoglobin","Hemoglobin_Method_Used",
            "Where_Results_Obtained_Before_Transfusion")
catvars<-c("Previous_Transfusion","Previous_Transfusion_When",
           "Anemia_Treatment","Who_Ordered_Transfusion",
           "Patient_Transfused_Where",
           "Where_Patient_Transfused_Start",
           "Hemoglobin_Method_Used",
           "Where_Results_Obtained_Before_Transfusion")
table4<-CreateTableOne(vars=listvars,data = table4.df,
                       factorVars = catvars,
                       includeNA = TRUE)
table4
```

##Figure 1. Bar graphs of blood products administered

```{r figure 1,echo=FALSE,warning=FALSE}
#red blood cells
bloodproducts<-subset(aim3_chki.tx.conf,select=c(1,2,112:114))
bloodproducts$redTotal<-as.character(bloodproducts$redTotal)
bloodproducts$redTotal[bloodproducts$redTotal=="5" | 
                         bloodproducts$redTotal=="6" | 
                         bloodproducts$redTotal=="7"]<-"5"
#(we note that there are 44 0's, but we make it NA because 
#we don't want to graph them)
ggplot(bloodproducts,aes(redTotal)) +
  geom_bar(fill=c("white","red","red1","red2","red3","red4")) +
  labs(x="# of Units",y="count",
       title="# of Patients with x Units of Red Blood Cells") +
  scale_x_discrete(labels=c("0","1","2","3","4","5+")) +
  geom_text(stat='count',aes(label=..count..,vjust=-.5))
#platelets
bloodproducts$pltTotal<-as.character(bloodproducts$pltTotal)
ggplot(bloodproducts,aes(pltTotal)) +
  geom_bar(fill=c("white","purple","purple2","purple4")) +
  labs(x="# of Units",y="count",
       title="# of Patients with x Units of Platelets") +
  scale_x_discrete(labels=c("0","1","2","4")) +
  geom_text(stat='count',aes(label=..count..,vjust=-.5))
#plasma
bloodproducts$ffpTotal<-as.character(bloodproducts$ffpTotal)
ggplot(bloodproducts,aes(ffpTotal)) +
  geom_bar(fill=c("white",
                  "slategray","slategray2","slategray3","slategray4")) +
  labs(x="# of Units",y="count",
       title="# of Patients with x Units of Plasma") +
  scale_x_discrete(labels=c("0","1","2","3","4")) +
  geom_text(stat='count',aes(label=..count..,vjust=-.5))
###Fig 2.  Hemoglobin increments###
#make the data set for the figure 2
hgb.increments<-data.frame(Location=aim3_chki.tx.conf$LOCATION,
                           Pretransfusion_Hgb=
                             aim3_chki.tx.conf$ATF_LastHemoglobinPriorTx,
                           Posttransfusion_Hgb=
                             aim3_chki.tx.conf$ATF_HbAfterTx,
                           Delta_Hgb=
                             aim3_chki.tx.conf$ATF_HbAfterTx - 
                             aim3_chki.tx.conf$ATF_LastHemoglobinPriorTx,
                           RBC_unit=aim3_chki.tx.conf$redTotal)
hgb.increments$DeltaHgb_div_RBCUnit<-
  hgb.increments$Delta_Hgb/hgb.increments$RBC_unit
#create a data frame without the NA or Inf observations 
#from the last column
hgb.inc.able<-subset(hgb.increments,!(is.na(DeltaHgb_div_RBCUnit)) & 
                       !(is.infinite(DeltaHgb_div_RBCUnit)))
#get the means of everything
sapply(hgb.inc.able,mean)
aggregate(hgb.inc.able[,2:6],list(hgb.inc.able$Location),mean)
#create a data frame so we can plot this in ggplot
groupall.df<-data.frame(Location=c(
  "Chris Hani","Chris Hani","Chris Hani","Chris Hani",
  "King Edward VIII","King Edward VIII",
  "King Edward VIII","King Edward VIII",
  "Overall","Overall","Overall","Overall"),
  Hgb_Tx=c(
    "Pre","Post","Delta","Delta/Unit",
    "Pre","Post","Delta","Delta/Unit",
    "Pre","Post","Delta","Delta/Unit"),
  means=c(6.65,9.26,2.6,1.09,
          6.93,8.79,1.86,.83,
          6.78,9.03,2.24,.96))
#create plot
groupall.df$Hgb_Tx<-factor(groupall.df$Hgb_Tx,
                           levels=c("Pre","Post","Delta","Delta/Unit"),
                           labels=c("Pre Hb (g/dL)","Post Hb (g/dL)",
                                    "Delta Hb (g/dL)",
                                    "Delta Hb (g/dL)/unit"))
ggplot(groupall.df,aes(x=Location,y=means,group=Hgb_Tx)) + 
  geom_point(aes(shape=Hgb_Tx,color=Hgb_Tx)) + 
  labs(x="Hospital",y="Mean Hemoglobin Level",
       title="Hemoglobin Increments") + 
  scale_y_continuous(breaks=seq(from=1,to=10))
```

##Crosstabs: Q6.2 (anemic curr.) and Q6.5 (med. rationale)
```{r crosstabs1,results="apsis"}
aim3_chki.tx.conf$Hemorrhage<-aim3_chki.tx.conf$ATF_MedicalRationaleForTx
aim3_chki.tx.conf$Hemorrhage<-gsub(
  ".*Hemorrhage.*","Hemorrhage",aim3_chki.tx.conf$Hemorrhage)
aim3_chki.tx.conf$Hemorrhage<-ifelse(
  aim3_chki.tx.conf$Hemorrhage=="Hemorrhage","Hemorrhage",
  ifelse(aim3_chki.tx.conf$Hemorrhage=="NA","NA","Not Hemorrhage"))
summary(freqlist(table(aim3_chki.tx.conf$ATF_IdAnemicDuringCurrPreg,
                       aim3_chki.tx.conf$Hemorrhage,
                       useNA = "ifany"),
                 labelTranslations = c("Anemic Curr. Preg.",
                                       "Bleeding This Preg.")))
```

##Crosstabs: Q6.2 (anemic curr.) and Q5.1a (bleeding this preg.)
```{r crosstabs2,results="apsis"}
summary(freqlist(table(aim3_chki.tx.conf$ATF_IdAnemicDuringCurrPreg,
                       aim3_chki.tx.conf$ATF_BleedingThisPreg,
                       useNA = "ifany"),
                 labelTranslations = c("Anemic Curr. Preg.",
                                       "Bleeding This Preg.")))
```

##Crosstabs: anemic.and.bleeding with Q5.1a (bleeding) and Q6.2 (anemic curr. preg.)
```{r crosstabs3,results="apsis"}
#new group variable
aim3_chki.tx.conf$anemic.and.bleeding<-NA
aim3_chki.tx.conf$anemic.and.bleeding<-as.character(
  aim3_chki.tx.conf$anemic.and.bleeding
)
aim3_chki.tx.conf$anemic.and.bleeding[
  aim3_chki.tx.conf$ATF_IdAnemicDuringCurrPreg=="01 Yes" & 
    aim3_chki.tx.conf$ATF_BleedingThisPreg=="01 Yes"
  ]<-"Both"
aim3_chki.tx.conf$anemic.and.bleeding[
  aim3_chki.tx.conf$ATF_IdAnemicDuringCurrPreg=="02 No" | 
    aim3_chki.tx.conf$ATF_IdAnemicDuringCurrPreg=="97 Unknown" | 
    is.na(aim3_chki.tx.conf$ATF_IdAnemicDuringCurrPreg) & 
    aim3_chki.tx.conf$ATF_BleedingThisPreg=="01 Yes"
  ]<-"Bleeding_Only"
aim3_chki.tx.conf$anemic.and.bleeding[
  aim3_chki.tx.conf$ATF_IdAnemicDuringCurrPreg=="01 Yes" & 
    aim3_chki.tx.conf$ATF_BleedingThisPreg=="02 No"
  ]<-"Anemia_Only"
aim3_chki.tx.conf$anemic.and.bleeding[
  aim3_chki.tx.conf$ATF_IdAnemicDuringCurrPreg=="02 No" | 
    aim3_chki.tx.conf$ATF_IdAnemicDuringCurrPreg=="97 Unknown" | 
    is.na(aim3_chki.tx.conf$ATF_IdAnemicDuringCurrPreg) & 
    aim3_chki.tx.conf$ATF_BleedingThisPreg=="02 No"
  ]<-"Neither"
#anemic.and.bleeding with Q5.1a (bleeding) and Q6.2 (anemic curr. preg.)
bleeding.this.preg.nona<-aim3_chki.tx.conf$ATF_BleedingThisPreg
bleeding.this.preg.nona[bleeding.this.preg.nona=="97 Unknown"]<-NA
summary(freqlist(table(aim3_chki.tx.conf$anemic.and.bleeding,
                       bleeding.this.preg.nona),
                 labelTranslations = c("Anemic*Bleeding",
                                       "Bleeding this Preg.")))
summary(freqlist(table(aim3_chki.tx.conf$anemic.and.bleeding,
                       aim3_chki.tx.conf$ATF_IdAnemicDuringCurrPreg),
                 labelTranslations = c("Anemic*Bleeding",
                                       "Anemic Curr. Preg.")))
```

##Crosstabs: Q6.5 (blood tx. rationale) and new group variabl
```{r crosstabs4,results="apsis"}
anemic.and.bleeding.nona<-subset(
  aim3_chki.tx.conf,!(is.na(anemic.and.bleeding))
)
summary(freqlist(table(anemic.and.bleeding.nona$anemic.and.bleeding,
                       anemic.and.bleeding.nona$ATF_MedicalRationaleForTx,
                       
                       useNA = "ifany"),
                 labelTranslations = c("Anemic*Bleeding",
                                       "Med. Rationale Tx.")))
```