---
title: "Table Shells"
output: word_document
---

```{r preliminary, include=FALSE}
library(readr)
library(lubridate) #to read the function parse_date_time
library(dplyr) # for %>%
library(tidyr) # for %>%
library(ggplot2)
library(gmodels)
library(knitr)
library(arsenal)
library(psych)
library(tableone)
library(officer)
library(flextable)
library(magrittr)
library(StatMeasures)
library(car)
library(rmarkdown)

aim3Dat_all <- read_csv("C:/Users/Adam/Documents/BSRI/TIP Stuff/aim3Dat_all.csv", 
                        col_types = 
                          cols(ATF_PMTCTStartDate = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_PMTCTStartDateUNK = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_LastCD4CountDate =
                                 col_date(format = "%d/%m/%Y"),
                            ATF_LastCD4CountDateUNK = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_LastViralLoadDate = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_LastViralLoadDateUNK = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_ARTStartDate = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_ARTStartDateUNK = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_HIVStatusOthTestDate =
                                 col_date(format = "%d/%m/%Y"),
                            ATF_HIVStatusOthTestDate2 = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_HIVStatusDelvAdmitDate =
                                 col_date(format = "%d/%m/%Y"),
                            ATF_HIVStatusBookingDate =
                                 col_date(format = "%d/%m/%Y"),
                            ATF_BookingDate =
                                 col_date(format = "%d/%m/%Y"),
                            ATF_EstDateDelivery = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_TodayDate = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_AdmDate = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_DschDate =
                                 col_date(format = "%d/%m/%Y"),
                            ATF_ComponentTxDate1 = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_ComponentTxDate2 = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_ComponentTxDate3 = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_ComponentTxDate4 = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_ComponentTxDate5 = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_ComponentTxDate6 = 
                                 col_date(format = "%d/%m/%Y"),
                            ATF_ComponentTxDate7 = 
                                 col_date(format = "%d/%m/%Y")))
View(aim3Dat_all)
#collapse hospital LOCATION column from four to three values
aim3Dat_all$LOCATION<-gsub(pattern="Groote Schuur Hospital",
                           replacement="Groote/Mowbray",
                           aim3Dat_all$LOCATION)
aim3Dat_all$LOCATION<-gsub(pattern="Mowbray Maternity Hospita",
                           replacement="Groote/Mowbray",
                           aim3Dat_all$LOCATION)
aim3Dat_all$LOCATION<-gsub(pattern="Chris Hani- Baragwanath H",
                           replacement="Chris Hani",
                           aim3Dat_all$LOCATION)
aim3Dat_all$LOCATION<-gsub(pattern="King Edward VIII Hospital",
                           replacement="King Edward",
                           aim3Dat_all$LOCATION)

###discarding rows that don't meet inclusion criteria
#aim3_inclusion<-aim3Dat_all[which(
  #aim3Dat_all$ATF_GestAgeWks < 26 & 
   # aim3Dat_all$ATF_Age > 17 & 
    #aim3Dat_all$ATF_Transfused=='01 Yes'),]

#isolate the sections#
#find out what the column names are and their indices
#colnames(aim3Dat_all)
aim3_sec0<-aim3Dat_all[c(48,1:47)]
aim3_sec0<-aim3_sec0[c(1,3,5,9:11)]
aim3_sec1<-aim3Dat_all[c(48,9,49:75)]
aim3_sec1<-aim3_sec1[c(-c(5:22,25))]
aim3_sec2<-aim3Dat_all[c(48,9,76:83)]
aim3_sec2<-aim3_sec2[c(1,2,6:8,10)]
aim3_sec3<-aim3Dat_all[c(48,9,84:107,185:206)]
aim3_sec3<-aim3_sec3[c(1,2,10:26)]
aim3_sec4<-aim3Dat_all[c(48,9,108:118,128:131)]
aim3_sec4<-aim3_sec4[c(1:10,14:16)]
aim3_sec5<-aim3Dat_all[c(48,9,210:236)]
aim3_sec5<-aim3_sec5[c(1:4,28)]
aim3_sec6<-aim3Dat_all[c(48,9,99,251:388)]
aim3_sec6<-aim3_sec6[c(1:2,4:11,13,14,21,22,23,34:44,52:56)]
aim3_sec7<-aim3Dat_all[c(48,9,260,313:388)]
aim3_sec7<-aim3_sec7[c(1:4,6,8,10,12,14,16,18,20,22,24,26,28,30,55:79)]

#split date variables with mixed date and time entries into two columns
aim3_sec0<-aim3_sec0 %>% 
  separate(CHARTABSTRATIONDATE,
           c("ChartAbstrationDate","ChartAbstrationTime"),
           sep=" ",extra="merge")
aim3_sec0<-aim3_sec0 %>% 
  separate(CONSENTDATE,
           c("ConsentDate","ConsentTime"),
           sep=" ",extra="merge")
aim3_sec0<-aim3_sec0 %>% 
  separate(CREATEDDATE,
           c("CreatedDate","CreatedTime"),
           sep=" ",extra="merge")

#change time variables to one format (military time)
aim3_sec0$ChartAbstrationTime<-
  parse_date_time(aim3_sec0$ChartAbstrationTime,c("HMS","HMS p"))
aim3_sec0$CreatedTime<-
  parse_date_time(aim3_sec0$CreatedTime,c("HMS","HMS p"))
aim3_sec0$ConsentTime<-
  parse_date_time(aim3_sec0$ConsentTime,c("HMS","HMS p"))

#discard the first part of these new time variables
aim3_sec0<-aim3_sec0 %>% 
  separate(ChartAbstrationTime,
           c("useless1","ChartAbstrationTime"),
           sep=" ",extra="merge")
aim3_sec0<-aim3_sec0 %>% 
  separate(CreatedTime,
           c("useless2","CreatedTime"),
           sep=" ",extra="merge")
aim3_sec0<-aim3_sec0 %>% 
  separate(ConsentTime,
           c("useless3","ConsentTime"),
           sep=" ",extra="merge")
aim3_sec0<-subset(aim3_sec0,
                    select=-c(useless1,useless2,useless3))
View(aim3_sec0)

attach(aim3_sec0)
#check if 'SUBJECT ID' and 'studyId' column are equal
all(SUBJECTID==studyId) #(TRUE)
#check for duplicates
which(duplicated(studyId)) 
#none are duplicates
detach(aim3_sec0)

#check if 'ChartAbstrationDate' and 'ConsentDate' are equal
#first convert them into dates
aim3_sec0$CreatedDate<-as.Date(aim3_sec0$CreatedDate,
                               format="%d/%m/%Y")
aim3_sec0$ChartAbstrationDate<-as.Date(aim3_sec0$ChartAbstrationDate,
                                      format="%d/%m/%Y")
aim3_sec0$ConsentDate<-as.Date(aim3_sec0$ConsentDate,
                                  format="%d/%m/%Y")
all(aim3_sec0$ChartAbstrationDate==aim3_sec0$ConsentDate) 
#(FALSE)
#which indeces are FALSE?
which(!(aim3_sec0$ChartAbstrationDate==aim3_sec0$ConsentDate))
#which indeces are NA?
which(is.na(aim3_sec0$ChartAbstrationDate==aim3_sec0$ConsentDate))
#drop time columns and SUBJECT ID column
aim3_sec0<-aim3_sec0[-c(3,5,7,9)]
#rearrange
aim3_sec0<-aim3_sec0[c(1,5,2,3,4)]

###section1###
#convert ATF_Date into a date column
aim3_sec1$ATF_TodayDate<-as.Date(aim3_sec1$ATF_TodayDate,
                                 format="%Y-%m-%d")
#check nonmissing values of nationalityDK, raceDK, gravidityDK,
  #parityDK
lapply(aim3_sec1[c(6,8,10)],function(x) which(!(is.na(x))))
#since the above vectors contain nothing relevant, let's delete them
aim3_sec1<-aim3_sec1[-c(6,8,10)]

###section2###
aim3_sec2$ATF_AdmDate<-as.Date(
  aim3_sec2$ATF_AdmDate,format="%d/%m/%Y"
)
aim3_sec2$ATF_DschgDate<-as.Date(
  aim3_sec2$ATF_DschgDate,format="%d/%m/%Y"
)
stay.length<-as.integer(aim3_sec2$ATF_DschgDate)-
  as.integer(aim3_sec2$ATF_AdmDate)
aim3_sec2$Stay_Length<-stay.length

###section3###
aim3_sec3$ATF_CompsThisPregType<-gsub("CompsThisPreg","",
                                      aim3_sec3$ATF_CompsThisPregType)
aim3_sec3$ATF_CompsThisAdmType<-gsub("CompsThisAdm","",
                                     aim3_sec3$ATF_CompsThisAdmType)
lapply(aim3_sec3[c(9,14,15,18)],function(x) which(!(is.na(x))))
#as categorical
gest.wks<-cut(aim3_sec3$ATF_GestAgeWks,
              breaks=c(-Inf,25,32,Inf),
              label=c("<26","26-32",">32"),
              right=FALSE)
#after running lapply, delete columns 14 and 18 since they are empty
aim3_sec3<-aim3_sec3[-c(14,18)]

#section4#
which(!(is.na(aim3_sec4$ATF_PMTCTStartDateUNK)))
#SAS frequency list
attach(aim3_sec4)
summary(freqlist(
  table(ATF_HIVStatusAtBooking,ATF_HIVStatusDelvAdmission,
        ATF_HIVStatusOthTest,ATF_HIVStatusOthTest2,
        useNA="ifany")
))
detach(aim3_sec4)

#section 5#
aim3_sec5$ATF_HemorrhageCause<-gsub("HemorrhageCause","",
                                    aim3_sec5$ATF_HemorrhageCause)
which(!(is.na(aim3_sec5$HemorrhageCauseOtherSpecify)))

#section 6#
aim3_sec6$ATF_MedicalRationaleForTx<-gsub(
  "MedRationaleTx","",aim3_sec6$ATF_MedicalRationaleForTx)
aim3_sec6$ATF_LastHemoglobinPriorTx<-as.numeric(
  aim3_sec6$ATF_LastHemoglobinPriorTx)
aim3_sec6$ATF_HbAfterTx<-as.numeric(
  aim3_sec6$ATF_HbAfterTx)
aim3_sec6$DeltaTx<-aim3_sec6$ATF_HbAfterTx - 
  aim3_sec6$ATF_LastHemoglobinPriorTx
lapply(aim3_sec6[c(9,10,13,14,19,20,22,24,25,28,30,31)], 
                  function(x) which(!(is.na(x))))
#delete columns 9, 13, 19, 24, 30 since they are empty
aim3_sec6<-aim3_sec6[-c(9,13,19,24,30)]

#section 7#
aim3_sec7$ATF_ComponentsTXDate1<-as.Date(
  aim3_sec7$ATF_ComponentsTXDate1,format="%d/%m/%Y")
aim3_sec7$ATF_ComponentsTXDate2<-as.Date(
  aim3_sec7$ATF_ComponentsTXDate2,format="%d/%m/%Y")
aim3_sec7$ATF_ComponentsTXDate3<-as.Date(
  aim3_sec7$ATF_ComponentsTXDate3,format="%d/%m/%Y")
aim3_sec7$ATF_ComponentsTXDate4<-as.Date(
  aim3_sec7$ATF_ComponentsTXDate4,format="%d/%m/%Y")
aim3_sec7$ATF_ComponentsTXDate5<-as.Date(
  aim3_sec7$ATF_ComponentsTXDate5,format="%d/%m/%Y")
```

## Table 1: Characteristics of the Study Population

```{r aim3_sec1}
table1.df<-data.frame(Age=aim3_sec1$ATF_Age,
                      Race=aim3_sec1$ATF_Race,
                      Gravidity=aim3_sec1$ATF_Gravidity,
                      Parity=aim3_sec1$ATF_Parity,
                      Gestation_Age_Weeks=aim3_sec3$ATF_GestAgeWks,
                      Booking_Status=aim3_sec3$ATF_BookingStatusAtAdm,
                      Prenatal_Visits=
                        aim3_sec3$ATF_NumVisitsAntenatalClinic,
                      Gestation_Age_Weeks_Grouped=gest.wks,
                      Length_of_Stay=stay.length,
                      Alive_at_Discharge=aim3_sec2$ATF_AliveAtDschg)
listvars<-c("Age","Race","Gravidity","Parity","Gestation_Age_Weeks",
            "Booking_Status","Gestation_Age_Weeks_Grouped","Length_of_Stay",
            "Prenatal_Visits","Alive_at_Discharge")
catvars<-c("Race","Booking_Status","Gestation_Age_Weeks_Grouped",
           "Alive_at_Discharge")
nonnormalvars<-c("Gravidity","Parity","Prenatal_Visits","Length_of_Stay")
table1<-CreateTableOne(vars=listvars,data = table1.df,factorVars = catvars,includeNA = TRUE)
table1.doc<-print(table1,nonnormal = nonnormalvars)
#(by hospital)
table1.df<-data.frame(Location=aim3_sec1$LOCATION,
  Age=aim3_sec1$ATF_Age,
  Race=aim3_sec1$ATF_Race,
  Gravidity=aim3_sec1$ATF_Gravidity,
  Parity=aim3_sec1$ATF_Parity,
  Gestation_Age_Weeks=aim3_sec3$ATF_GestAgeWks,
  Booking_Status=aim3_sec3$ATF_BookingStatusAtAdm,
  Prenatal_Visits=aim3_sec3$ATF_NumVisitsAntenatalClinic,
  Gestation_Age_Weeks_Grouped=gest.wks,
  Length_of_Stay=stay.length,
  Alive_at_Discharge=aim3_sec2$ATF_AliveAtDschg)
listvars<-c("Age","Race","Gravidity","Parity","Gestation_Age_Weeks",
            "Booking_Status","Gestation_Age_Weeks_Grouped","Length_of_Stay",
            "Prenatal_Visits","Alive_at_Discharge")
catvars<-c("Location",
  "Race","Booking_Status","Gestation_Age_Weeks_Grouped",
  "Alive_at_Discharge")
nonnormalvars<-c("Gravidity","Parity","Prenatal_Visits","Length_of_Stay")
table1<-CreateTableOne(vars=listvars,data = table1.df,factorVars = catvars,
                       includeNA = TRUE,strata = "Location",test=FALSE)
print(table1,nonnormal = nonnormalvars)
```

## Table 1 Plots:

```{r table 1 plots}
ggplot(aim3_sec1,aes(ATF_Age)) + 
  geom_histogram() + 
  labs(x="Age in Years",y="counts",title="Age of Mothers")
ggplot(aim3_sec1,aes(LOCATION,ATF_Age)) + 
  geom_boxplot(fill=c("chocolate","green","khaki")) +
  labs(x="Location",y="Age in Years",title="Age of Mothers by Location")
ggplot(aim3_sec1,aes(ATF_Race)) +
  geom_bar(fill=c("black","white","brown","yellow","gray")) +
  labs(x="Race",y="counts",title="Race of Mothers") +
  scale_x_discrete(labels=c("Black","White","Coloured","Asian","NA")) +
  geom_text(stat='count',aes(label=..count..,vjust=-.3))
ggplot(aim3_sec1, aes(fill=ATF_Race, x=LOCATION)) + 
  geom_bar() + 
  scale_fill_manual(values=c("01 Black"="black",
                           "02 White"="white",
                           "03 Coloured"="brown",
                           "04 Asian"="yellow",
                           "NA"="gray")) +
  labs(x="Hospital",y="counts",title="Race of Mothers by Location") + 
  geom_text(stat='count',aes(label=..count..,vjust=-.3))
```

##Table 2:

```{r table 2}
table2.df<-data.frame(Primary_Indication_for_Blood_Transfusion=
                        aim3_sec6$ATF_Transfused,
                      Blood_Transfusion_Rationale=
                        aim3_sec6$ATF_MedicalRationaleForTx,
                      Anemic_Current_Pregnancy=
                        aim3_sec6$ATF_IdAnemicDuringCurrPreg,
                      Anemia_Etiology=
                        aim3_sec6$ATF_ChronicAnemiaType,
                      Hemorrhage=
                        aim3_sec5$ATF_BleedingThisPreg,
                      Hemorrhage_Etiology=
                        aim3_sec5$ATF_HemorrhageCause)
listvars<-c("Primary_Indication_for_Blood_Transfusion",
            "Blood_Transfusion_Rationale","Anemic_Current_Pregnancy",
            "Anemia_Etiology","Hemorrhage","Hemorrhage_Etiology")
catvars<-c("Primary_Indication_for_Blood_Transfusion",
           "Blood_Transfusion_Rationale","Anemic_Current_Pregnancy",
           "Anemia_Etiology","Hemorrhage","Hemorrhage_Etiology")
table2<-CreateTableOne(vars=listvars,data=table2.df,factorVars = catvars,
                       includeNA = TRUE)
table2
```

##Table 3: Complications During Current Pregnancy

```{r table 3}
table3.df<-data.frame(Other_Nonhemorrhagic_Obstetric_Complication=
                        aim3_sec3$ATF_CompsThisPreg,
                      Nonhemorrhagic_Obstetric_Complications=
                        aim3_sec3$ATF_CompsThisPregType,
                      Other_Obstetric_Complication=
                        aim3_sec3$ATF_CompsThisAdm,
                      Obstetric_Complications=
                        aim3_sec3$ATF_CompsThisAdmType)
listvars<-c("Other_Nonhemorrhagic_Obstetric_Complication",
            "Nonhemorrhagic_Obstetric_Complications",
            "Other_Obstetric_Complication",
            "Obstetric_Complications")
catvars<-c("Other_Nonhemorrhagic_Obstetric_Complication",
            "Nonhemorrhagic_Obstetric_Complications",
            "Other_Obstetric_Complication",
            "Obstetric_Complications")
table3<-CreateTableOne(vars=listvars,data = table3.df,factorVars = catvars,
                       includeNA = TRUE)
table3
```

##Table 4: Miscellaneous

```{r table 4}
table4.df<-data.frame(Previous_Transfusion=
                        aim3_sec6$ATF_TransfusePriorToCurr,
                      Previous_Transfusion_When=
                        aim3_sec6$ATF_TransfusedPriorWhen,
                      Anemia_Treatment=
                        aim3_sec6$ATF_OnHematinicRxDuringPreg,
                      Who_ordered_transfusion=
                        aim3_sec6$ATF_TxHighestLevelDiscuss,
                      Transfused_where_pt.a=
                        aim3_sec6$ATF_PtTransfusedAt,
                      Transfused_where_pt.b=
                        aim3_sec6$ATF_WherePtTxStart,
                      PreTransfusion_Hemoglobin=
                        aim3_sec6$ATF_LastHemoglobinPriorTx,
                      Hemoglobin_Method_Used=
                        aim3_sec6$ATF_HbMethodUsed,
                      Results_Obtained_Before_Transfusion=
                        aim3_sec6$ATF_WhereResultsObtainedPriorTx)
listvars<-c("Previous_Transfusion","Previous_Transfusion_When",
             "Anemia_Treatment","Who_ordered_transfusion",
             "Transfused_where_pt.a","Transfused_where_pt.b",
             "PreTransfusion_Hemoglobin","Hemoglobin_Method_Used",
             "Results_Obtained_Before_Transfusion")
catvars<-c("Previous_Transfusion","Previous_Transfusion_When",
            "Anemia_Treatment","Who_ordered_transfusion",
            "Transfused_where_pt.a","Transfused_where_pt.b",
            "Hemoglobin_Method_Used","Results_Obtained_Before_Transfusion")
table4<-CreateTableOne(vars=listvars,data = table4.df,factorVars = catvars,
                       includeNA = TRUE)
table4
```

##Figure 1. Bar Graphs of Blood Products Administered

```{r code Figure 1, echo=FALSE}
#red blood cells
bloodproducts<-subset(aim3_sec7,select=c(1,2,40:42))
bloodproducts$redTotal<-as.character(bloodproducts$redTotal)
bloodproducts$redTotal[bloodproducts$redTotal=="5" | 
                           bloodproducts$redTotal=="6" | 
                           bloodproducts$redTotal=="7"]<-"5"
#(we note that there are 44 0's, but we make it NA because 
    #we don't want to graph them)
ggplot(bloodproducts,aes(redTotal)) +
  geom_bar(fill=c("white","red","red1","red2","red3","red4")) +
  labs(x="# of Units",y="count",
       title="# of Patients with x Units of Red Blood Cells") +
  scale_x_discrete(labels=c("0","1","2","3","4","5+")) +
  geom_text(stat='count',aes(label=..count..,vjust=-.4))
#platelets
bloodproducts$pltTotal<-as.character(bloodproducts$pltTotal)
ggplot(bloodproducts,aes(pltTotal)) +
  geom_bar(fill=c("white","purple","purple2","purple4")) +
  labs(x="# of Units",y="count",
       title="# of Patients with x Units of Platelets") +
  scale_x_discrete(labels=c("0","1","2","4")) +
  geom_text(stat='count',aes(label=..count..,vjust=-.4))
#plasma
bloodproducts$ffpTotal<-as.character(bloodproducts$ffpTotal)
ggplot(bloodproducts,aes(ffpTotal)) +
  geom_bar(fill=c("white",
                  "slategray","slategray2","slategray3","slategray4")) +
  labs(x="# of Units",y="count",
       title="# of Patients with x Units of Plasma") +
  scale_x_discrete(labels=c("0","1","2","3","4")) +
  geom_text(stat='count',aes(label=..count..,vjust=-.4))
```

##Figure 2: Hemoglobin Increments

```{r code, fig.width=6.5}
#check for outliers
#plot(aim3_sec6$ATF_LastHemoglobinPriorTx)
#plot(aim3_sec6$ATF_HbAfterTx)
#boxplot.stats(aim3_sec6$ATF_LastHemoglobinPriorTx)
#which(grepl(77.5,aim3_sec6$ATF_LastHemoglobinPriorTx))
#make the data set for the figure 2
hgb.increments<-data.frame(Location=aim3_sec6$LOCATION,
                           Pretransfusion_Hgb=
                             aim3_sec6$ATF_LastHemoglobinPriorTx,
                           Posttransfusion_Hgb=aim3_sec6$ATF_HbAfterTx,
                           Delta_Hgb=aim3_sec6$ATF_HbAfterTx - 
                             aim3_sec6$ATF_LastHemoglobinPriorTx,
                           RBC_unit=aim3_sec7$redTotal)
hgb.increments$DeltaHgb_div_RBCUnit<-
  hgb.increments$Delta_Hgb/hgb.increments$RBC_unit
#create a data frame without the NA or Inf observations 
  #from the last column
hgb.inc.able<-subset(hgb.increments,!(is.na(DeltaHgb_div_RBCUnit)) & 
                       !(is.infinite(DeltaHgb_div_RBCUnit)))
#get the means of everything
#sapply(hgb.inc.able,mean)
#aggregate(hgb.inc.able[,2:6],list(hgb.inc.able$Location),mean)
#create a data frame so we can plot this in ggplot
groupall.df<-data.frame(Location=c(
  "Chris Hani","Chris Hani","Chris Hani","Chris Hani",
  "Groote/Mowbray","Groote/Mowbray","Groote/Mowbray","Groote/Mowbray",
  "King Edward VIII","King Edward VIII",
  "King Edward VIII","King Edward VIII",
  "Overall","Overall","Overall","Overall"),
  Hgb_Tx=c(
    "Pre","Post","Delta","Delta/Unit",
    "Pre","Post","Delta","Delta/Unit",
    "Pre","Post","Delta","Delta/Unit",
    "Pre","Post","Delta","Delta/Unit"),
  means=c(6.6,9.26,2.66,1.12,
          6.61,8.92,2.3,1.14,
          6.93,8.79,1.86,.83,
          6.74,9.02,2.28,1))
#create plot
groupall.df$Hgb_Tx<-factor(groupall.df$Hgb_Tx,
                           levels=c("Pre","Post","Delta","Delta/Unit"),
                           labels=c("Pre Hb (g/dL)","Post Hb (g/dL)",
                                    "Delta Hb (g/dL)",
                                    "Delta Hb (g/dL)/unit"))
ggplot(groupall.df,aes(x=Location,y=means,group=Hgb_Tx)) + 
  geom_point(aes(shape=Hgb_Tx,color=Hgb_Tx)) + 
  scale_y_continuous(breaks=seq(1:10)) + 
  labs(x="Hospital",y="Mean Hemoglobin Level",
       title="Hemoglobin Increments") + 
  scale_x_discrete(c("Chris Hani","Groote/Mowbray","King Edward","Overall"))
```

##Cross-tabs of Q6.2 and Q6.5

```{r crosstabs1,results="asis"}
aim3_sec6$Hemorrhage<-aim3_sec6$ATF_MedicalRationaleForTx
aim3_sec6$Hemorrhage<-gsub(
  ".*Hemorrhage.*","Hemorrhage",aim3_sec6$Hemorrhage)
aim3_sec6$Hemorrhage<-ifelse(
  aim3_sec6$Hemorrhage=="Hemorrhage","Hemorrhage",
  ifelse(aim3_sec6$Hemorrhage=="NA","NA","Not Hemorrhage"))
summary(freqlist(table(aim3_sec6$ATF_IdAnemicDuringCurrPreg,
                       aim3_sec6$Hemorrhage,
                       useNA = "ifany"),
                 labelTranslations = c("Anemic Curr. Preg.",
                                       "Bleeding This Preg.")))
```

##Cross-tabs of Q6.2 and Q5.1a
``` {r crosstabs2,results="asis"}
summary(freqlist(table(aim3_sec6$ATF_IdAnemicDuringCurrPreg,
                       aim3_sec5$ATF_BleedingThisPreg,
                       useNA = "ifany"),
                 labelTranslations = c("Anemic Curr. Preg.","Bleeding This Preg.")))
```

##"Other" Specified for Table 2
``` {r others1, results="asis"}
summary(freqlist(table(aim3_sec5$ATF_HemorrhageCause,
                       aim3_sec5$HemorrhageCauseOtherSpecify),
                 labelTranslations = c("Hemorrhage Cause w/ 'Other'","Other Specify")))
```

##"Other" Specified for Table 3
``` {r others2,results="asis"}
summary(freqlist(table(aim3_sec3$ATF_CompsThisPregType,
                       aim3_sec3$ComplicationsThisPregnancySP),
                 labelTranslations = c("Preg. Complications w/ 'Other'","'Other' Specified")))
summary(freqlist(table(aim3_sec3$ATF_CompsThisAdmType,
                       aim3_sec3$ComplicationsThisAdmissionSP),
                 labelTranslations = c("Adm. Complications w/ 'Other'","'Other' Specified")))
```